8.2=docker.hypernode.com/byteinternet/hypernode-bookworm-docker-php82-mysql80:latest
8.3=docker.hypernode.com/byteinternet/hypernode-bookworm-docker-php83-mysql80:latest
8.4=docker.hypernode.com/byteinternet/hypernode-bookworm-docker-php84-mysql80:latest
